---
name: CI for ssl_verify_fun.erl
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [17.1, 17.3, 18.0, 18.1, 19.0, 19.3, 20.0, 20.3, 21.0.2, 22.3, 23.1]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 dialyzer
      - run: rebar3 eunit
